PREFIX_TOKEN = "users"

AUTH_TOKEN_AUDIENCE = f"{PREFIX_TOKEN}:auth"
RESET_PASSWORD_TOKEN_AUDIENCE = f"{PREFIX_TOKEN}:reset"
VERIFY_USER_TOKEN_AUDIENCE = f"{PREFIX_TOKEN}:verify"
STATE_TOKEN_AUDIENCE = f"{PREFIX_TOKEN}:oauth-state"

TOKEN_LIFETIME = 3600
